Configure openshift hooks and stuff.

diff --git a/.openshift/action_hooks/start b/.openshift/action_hooks/start
--- a/.openshift/action_hooks/start
+++ b/.openshift/action_hooks/start
@@ -1,5 +1,55 @@
 #!/bin/bash
 # The logic to start up your application should be put in this
 # script. The application will work only if it binds to
-# $OPENSHIFT_DIY_IP:8080
-nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
+# $OPENSHIFT_INTERNAL_IP:8080
+
+# debug
+# set -x
+
+#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
+. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config
+
+if [[ ! $? -eq 0 ]]; then
+	exit $?
+fi
+
+if [[ ! -f $PLAY_COMMAND ]]; then
+	echo "Error: couldn't find play executable at $PLAY_COMMAND"
+	exit 1
+fi
+
+## stop play application
+${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: could not stop play application"
+	exit 1
+fi
+
+cd "$OPENSHIFT_REPO_DIR"
+
+# clean everything
+echo "$PLAY_COMMAND clean" >> $LOG_FILE
+$PLAY_COMMAND clean &> $LOG_FILE
+
+#echo "$PLAY_COMMAND deps $DEPS_PARAMS -Divy.home=${OPENSHIFT_TMP_DIR}ivy2/" >> $LOG_FILE
+#$PLAY_COMMAND deps $DEPS_PARAMS -Divy.home=${OPENSHIFT_TMP_DIR}ivy2/ &> $LOG_FILE
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: could not update dependencies"
+	echo "Error executing '$PLAY_COMMAND $DEPS_PARAMS'"
+	exit 1
+fi
+
+#export PLAY_LOG_PATH=${OPENSHIFT_DIY_LOG_DIR}
+export PLAY_LOG_PATH=${OPENSHIFT_DIY_DIR}logs/
+echo "$PLAY_COMMAND start" >> $LOG_FILE
+nohup bash -c "$PLAY_COMMAND start &> $LOG_FILE" &> /dev/null &
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: starting play application"
+	echo "Error executing '$APP_COMMAND'"
+	exit 1
+fi
+
+exit 0
diff --git a/.openshift/action_hooks/stop b/.openshift/action_hooks/stop
--- a/.openshift/action_hooks/stop
+++ b/.openshift/action_hooks/stop
@@ -1,10 +1,66 @@
 #!/bin/bash
-source $OPENSHIFT_CARTRIDGE_SDK_BASH
-
 # The logic to stop your application should be put in this script.
-if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]
-then
-    client_result "Application is already stopped"
-else
-    kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
+
+# debug
+# set -x
+
+#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
+. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config
+
+if [[ ! $? -eq 0 ]]; then
+	exit $?
 fi
+
+cd "$OPENSHIFT_REPO_DIR"
+
+#kill play if it was running
+if [[ -f "server.pid" ]]; then
+
+	if [[ ! -f $PLAY_COMMAND ]]; then
+		echo "Error: couldn't find play executable at $PLAY_COMMAND"
+		exit 1
+	fi
+
+	echo "Stopping play application"
+	bash -c "$PLAY_COMMAND stop &> $LOG_FILE" &> /dev/null
+
+	#manually remove server.pid if it's there
+	if [[ -f "server.pid" ]]; then
+		echo "Manually removing server.pid file"
+		bash -c "rm server.pid &> $LOG_FILE" &> /dev/null
+	fi
+fi
+
+#it survived, try to kill it manually
+if [[ -n `ps -A | grep ' java$'` ]]; then
+
+	# try 5 times to kill it
+	for c in `seq 1 5`; do
+		echo "Trying to kill java proccess, attemp number $c"
+		bash -c "pkill java &> $LOG_FILE" &> /dev/null
+		sleep $c
+		#killed it
+		if [[ -z `ps -A | grep ' java$'` ]]; then
+			exit 0
+		fi
+	done
+
+	# try 5 times to kill it
+	for c in `seq 1 5`; do
+		echo "Trying to kill java proccess with -SIGKILL, attemp number $c"
+		bash -c "pkill -SIGKILL java &> $LOG_FILE" &> /dev/null
+		sleep $c
+		#killed it
+		if [[ -z `ps -A | grep ' java$'` ]]; then
+			exit 0
+		fi
+	done
+
+	#couldn't kill it
+	if [[ -n `ps -A | grep ' java$'` ]]; then
+		echo "Error: could not stop play application, error executing 'pkill java'"
+		exit 1
+	fi
+fi
+
+exit 0
